web/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name = "accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name = "accounts/logout.html"), name='logout'),
]

web/service/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, re_path, reverse, include
from service import views

app_name = "service"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommend/', views.recommend, name='recommend'),
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from service import views

app_name = "web"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('service/', include('service.urls')),
]

web/accounts/models.py
from django.db import models

web/service/models.py
from django.db import models
from django.contrib.auth.models import User

class Review(models.Model):
    objects = models.Manager()
    image = models.CharField(max_length=100)
    userid = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    designer = models.CharField(max_length=100)
    price = models.FloatField()
    score = models.FloatField()

web/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

class SignupForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('ID already Existed')
        return username

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise forms.ValidationError('Password Incorrect')
        return password2

    def signup(self):
        if self.is_valid():
            return User.objects.create_user(
                username=self.cleaned_data['username'],
                password=self.cleaned_data['password2']
            )

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

web/service/forms.py
from django import forms
from .models import Review
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields =('userid','image','title','designer','price','score',)

web/accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login as django_login, logout as django_logout, authenticate

def signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)
        if signup_form.is_valid():
            signup_form.signup()
            return render(request, 'service/review.html')
    else:
        signup_form = SignupForm()

    context = {
        'signup_form': signup_form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(
                username=username,
                password=password
            )
            if user:
                django_login(request, user)
                return redirect('mypage')
            login_form.add_error(None, '아이디 또는 비밀번호가 올바르지 않습니다')
    else:
        login_form = LoginForm()
    context = {
        'login_form': login_form,
    }
    return render(request, 'accounts/login.html', context)

web/service/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render
from .models import Review
from .forms import ReviewForm
from .recommend import Recommend

# Create your views here.

def recommend(request):
    rec = Recommend()
    name = str(request.user)
    try:
        recommend = rec.get_recommend_list(name)
        print(recommend)
        return render(request, 'service/recommend.html', {'recommend':recommend})
    except:
        print("no data")
        return render(request, 'service/recommend.html')   
    
def review(request):
    review = Review.objects.all()
    return render(request, 'service/review.html', {'review':review})

def create_review(request):
    data = dict()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            Reviews = Review.objects.all()
            data['html_review'] = render_to_string('service/review.html', {
                'Reviews': Reviews
            })
        else:
            data['form_is_valid'] = False
    else:
        form = ReviewForm()
    print(request.user)
    form = ReviewForm()
    context = {'form' : form}
    data['html_form'] = render_to_string('service/create_review.html', context, request = request,)
    return JsonResponse(data)

web/accounts/templates/accounts/form.html
<form action="" method="post">
	{% csrf_token %}
	{% for field in form %}
		<div class="form-group{% if field.errors %} has-error{% endif %}">
			{{ field.label_tag }}
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	{% endfor %}

	{% if form.non_field_errors %}
		{% for error in login_form.non_field_errors %}
		<p class="text-danger"><b>{{ error }}</b></p>
		{% endfor %}
	{% endif %}
	<button class="btn btn-primary btn-block">{{ submit_title }}</button>
</form>

web/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row" id="login">
    <div class="col"></div>
    <div class="col-3" id="login-subject">
        <div class="alert alert-primary" role="alert">
            Please enter your ID and Password
        </div>
        <form action="" method="POST" id="login-form">
            {% csrf_token %}
            {{form.as_p}}
            <ul>
                <input type="submit" value="login" class="btn btn-outline-primary"/>
                <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">signup</a>
            </ul>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

web/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row" id="logout">
    <div class="col"></div>
    <div class="'col-6'">
        <div class="alert alert-primary" role="alert">
            Logout success
        </div>
        <a href="{% url 'accounts:login'%}" class="btn btn-outline-success">login</a>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

web/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}
{% block content %}
<div class="signup" id="signup-form">
	<form action="" method="POST">
		{% csrf_token %}
		{% for field in signup_form %}
			<div class="form-group{% if field.errors %} has-error{% endif %}">
				{{ field.label_tag }}
				{{ field }}
				{% if field.errors %}
					{% for error in field.errors %}
					<span class="help-block">{{ error }}</span>
					{% endfor %}
				{% endif %}
			</div>
		{% endfor %}

		{% if signup_form.non_field_errors %}
			{% for error in login_form.non_field_errors %}
			<p class="text-danger"><b>{{ error }}</b></p>
			{% endfor %}
		{% endif %}
		<button class="btn btn-primary btn-block">회원가입</button>
	</form>
</div>
{% endblock %}

web/service/templates/service/create.html
{% load widget_tweaks %}

<form method="post">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Review</button>
  </div>
</form>

web/service/templates/service/create_review.html
{% load widget_tweaks %}

<form method="post" action="{% url 'service:create_review' %}" class="js-review-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new Review</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Review</button>
  </div>
</form>

web/service/templates/service/recommend.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="recommend-box">
    <center><h1 class="page-header">Recommendation</h1></center>
</div>
<div class="row" id="recommend-list">
    <div class="col">
    <div class="row">
        <div class="card-group">
            {% for rec in recommend %}
            <div class="card">
                <img src="{{ rec.2 }}" class="card-img-top" alt="...">
                <div class="card-body">
                <p class="card-text"><strong>{{ rec.1 }}</strong> <br>Designer : <strong>{{rec.3}}</strong> <br> Expected Rating : <strong>{{rec.0|floatformat}}</strong></p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

web/service/templates/service/review.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<script src="{% static 'service/js/review.js' %}" type="text/javascript"></script>

<div class="review-box">
    <center><h1 class="page-header">Reviews</h1></center>
    <p>
      <button type="button" class="btn btn-primary js-create-review" data-url="{% url 'service:create_review' %}">
          <span class="glyphicon glyphicon-plus"></span>
          New Review
      </button>
    </p>
    <table class="table" id="review-table">
    <thead>
      <tr>
        <th>Image</th>
        <th>Title</th>
        <th>Designer</th>
        <th>Price</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {% for rev in review %}
        {% if rev.userid == user.username %}
        <tr>
          <td valign=middle>
            <img src="{{ rev.image }}" width=100 height=100>
          </td>
          <td>{{ rev.title }}</td>
          <td>{{ rev.designer }}</td>
          <td>₩{{ rev.price|intcomma }}</td>
          <td>{{ rev.score }}</td>
        </tr>
        {% endif %}
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">No Reviews</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>

    <div class="modal fade" id="modal-review">
        <div class="modal-dialog">
            <div class="modal-content"></div>
        </div>
    </div>
</div>
{% endblock %}